import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import contactsRouter from "./contacts";
import companiesRouter from "./companies";
import dealStagesRouter from "./deal-stages";
import dealsRouter from "./deals";
import tasksRouter from "./tasks";
import activitiesRouter from "./activities";
import campaignsRouter from "./campaigns";
import dashboardRouter from "./dashboard";
import trackingRouter from "./tracking";
import unsubscribeRouter from "./unsubscribe";
import searchRouter from "./search";
import notesRouter from "./notes";
import reportsRouter from "./reports";
import dashboardsRouter from "./dashboards";
import teamRouter from "./team";
import sequencesRouter from "./sequences";
import scheduledExportsRouter from "./scheduled-exports";
import auditRouter from "./audit";
import blockedDomainsRouter from "./blocked-domains";
import customFieldsRouter from "./custom-fields";
import aiSuggestionsRouter from "./ai-suggestions";
import storageRouter from "./storage";
import attachmentsRouter from "./attachments";
import migrateRouter from "./migrate";
import segmentsRouter from "./segments";
import messagesRouter from "./messages";
import integrationsRouter from "./integrations";
import automationsRouter from "./automations";
import settingsRouter from "./settings";
import gmailRouter from "./gmail";
import emailInboundRouter from "./email-inbound";
import meetingSummaryRouter from "./meeting-summary";
import nextStepsRouter from "./next-steps";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/users", usersRouter);
router.use("/contacts", contactsRouter);
router.use("/companies", companiesRouter);
router.use("/deal-stages", dealStagesRouter);
router.use("/deals", dealsRouter);
router.use("/tasks", tasksRouter);
router.use("/activities", activitiesRouter);
router.use("/campaigns", campaignsRouter);
router.use("/dashboard", dashboardRouter);
router.use("/track", trackingRouter);
router.use(unsubscribeRouter);
router.use("/segments", segmentsRouter);
router.use("/search", searchRouter);
router.use("/notes", notesRouter);
router.use("/reports", reportsRouter);
router.use("/dashboards", dashboardsRouter);
router.use("/team", teamRouter);
router.use("/sequences", sequencesRouter);
router.use("/scheduled-exports", scheduledExportsRouter);
router.use("/audit", auditRouter);
router.use("/blocked-domains", blockedDomainsRouter);
router.use("/custom-fields", customFieldsRouter);
router.use("/ai/suggestions", aiSuggestionsRouter);
router.use(storageRouter);
router.use("/attachments", attachmentsRouter);
router.use("/migrate", migrateRouter);
router.use("/messages", messagesRouter);
router.use("/integrations", integrationsRouter);
router.use("/automations", automationsRouter);
router.use("/settings", settingsRouter);
router.use("/gmail", gmailRouter);
router.use("/email/inbound", emailInboundRouter);
router.use("/ai/meeting-summary", meetingSummaryRouter);
router.use("/next-steps", nextStepsRouter);

export default router;
