import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import contactsRouter from "./contacts";
import companiesRouter from "./companies";
import dealStagesRouter from "./deal-stages";
import dealsRouter from "./deals";
import tasksRouter from "./tasks";
import activitiesRouter from "./activities";
import campaignsRouter from "./campaigns";
import dashboardRouter from "./dashboard";
import trackingRouter from "./tracking";
import searchRouter from "./search";
import notesRouter from "./notes";
import reportsRouter from "./reports";
import teamRouter from "./team";
import sequencesRouter from "./sequences";
import scheduledExportsRouter from "./scheduled-exports";
import auditRouter from "./audit";
import blockedDomainsRouter from "./blocked-domains";
import customFieldsRouter from "./custom-fields";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/users", usersRouter);
router.use("/contacts", contactsRouter);
router.use("/companies", companiesRouter);
router.use("/deal-stages", dealStagesRouter);
router.use("/deals", dealsRouter);
router.use("/tasks", tasksRouter);
router.use("/activities", activitiesRouter);
router.use("/campaigns", campaignsRouter);
router.use("/dashboard", dashboardRouter);
router.use("/track", trackingRouter);
router.use("/search", searchRouter);
router.use("/notes", notesRouter);
router.use("/reports", reportsRouter);
router.use("/team", teamRouter);
router.use("/sequences", sequencesRouter);
router.use("/scheduled-exports", scheduledExportsRouter);
router.use("/audit", auditRouter);
router.use("/blocked-domains", blockedDomainsRouter);
router.use("/custom-fields", customFieldsRouter);

export default router;
